### ISSUE TITLE
Activity.Start() called from ActivityStop Function

### ISSUE THREAD

**Issue by JarrodJ83** [jbogard/NServiceBus.Extensions.Diagnostics#1]
Was looking at your code as I would love to apply the same type of functionality for [Pulsar.Client](https://github.com/fsharplang-ru/pulsar-client-dotnet). Noticed this and figured I would let you know. I am guessing you're looking to stop the Activity here, not start it.

https://github.com/jbogard/NServiceBus.Extensions.Diagnostics/blob/960fd363dab5a0745518bf36b2ed2f2180abe726/src/NServiceBus.Extensions.Diagnostics/OutgoingPhysicalMessageDiagnostics.cs#L95

Great work on all of this, btw! Blog series on this topic was great.

**Comment by jbogard** [comment]
Sigh. Good catch.

**Comment by jbogard** [comment]
Fixed!
