### ISSUE TITLE
Activity Baggage Order Reversed

### ISSUE THREAD

**Issue by mitchell-etter** [jbogard/NServiceBus.Extensions.Diagnostics#10]
Upon receiving a message, the order of the Activity.Baggage collection is reversed from what is in the message header. Attached is an example showing the baggage being reversed. [BaggageOrderExample.zip](https://github.com/jbogard/NServiceBus.Extensions.Diagnostics/files/7990196/BaggageOrderExample.zip)

The Activity.AddBaggage method adds to the front of the list (LIFO): https://github.com/dotnet/runtime/pull/42659. It could reverse the order of the baggage if the collection is being copied: https://github.com/jbogard/NServiceBus.Extensions.Diagnostics/blob/40a10cb898c4493aaf6eca4d30fc368f99456c83/src/NServiceBus.Extensions.Diagnostics/IncomingPhysicalMessageDiagnostics.cs#L85-L88

In fact, ASP.NET Core had the same issue: https://github.com/dotnet/aspnetcore/issues/26303. It was fixed by reversing the iteration order: https://github.com/dotnet/aspnetcore/pull/26302/files#diff-f4b6e9bc19da99141d4427d88673ed12fdf3474082f571b027a583cb6959ca99

**Comment by jbogard** [comment]
PR?

**Comment by mitchell-etter** [comment]
I can have a pull request ready in the next few days.
