### ISSUE TITLE
NServiceBus v8 Support

### ISSUE THREAD

**Issue by buvinghausen** [jbogard/NServiceBus.Extensions.Diagnostics#22]
@jbogard with the NServiceBus v8 RC on NuGet I figured it would be nice to get a v8 compatible version of this library.

I was going to take a stab at it if there wasn't anything big going on but it looks like the OutboundRoutingPolicy property on the TransportInfrastructure class was obsoleted and so the messaging.destination_kind tag will require some refactoring.

For the time being I have just forked the code and removed that tag and everything else seems to be working as expected.

**Comment by jbogard** [comment]
I'll take a look but tbqh NServiceBus 8 added a *ton* of support for System.Diagnostics and the rest, so my plan is to look to see what they've implemented and delete anything in this library that's a duplicate.

**Comment by jbogard** [comment]
Confirmed on my side, all the stuff is built in that you need. This package is no longer needed 🥇

**Comment by jbogard** [comment]
see: https://docs.particular.net/nservicebus/operations/opentelemetry
