### ISSUE TITLE
Question: Activity.ParentId correlation

### ISSUE THREAD

**Issue by buvinghausen** [jbogard/NServiceBus.Extensions.Diagnostics#4]
My expectation is when I hit an HTTP endpoint the source Activity.Id would become the Activity.ParentId for every single operation downstream no matter how many messages get ping ponged around.

Without polluting this issue with log statements here's the gist

HTTP Source:
Activity.Id: 00-86853ea669f5b44d87ae18490c1f532d-f83ce54202628540-01

Web.Send:
Activity.Id: 00-86853ea669f5b44d87ae18490c1f532d-5bc5e98a8ab5c247-01
Activity.ParentId: 00-86853ea669f5b44d87ae18490c1f532d-f83ce54202628540-01

Worker.Handle:
Activity.Id: 00-86853ea669f5b44d87ae18490c1f532d-a4fbf3df37e05445-01
Activity.ParentId: 00-86853ea669f5b44d87ae18490c1f532d-5bc5e98a8ab5c247-00

The Activity.ParentId correlates as expected downstream for all in-process activities and I see the traceparent header in the outgoing message but it has the value of the Activity.Id from the bus.send operation. So my question is shouldn't it have the Activity.ParentId there if present to make the full chain of custody easier to query?

**Comment by jbogard** [comment]
That's not quite how distributed traces work. The parent ID is the previous activity's ID. When a new activity is created, its new ID is always generated, and the parent is set from `Activity.Current`:

https://github.com/dotnet/runtime/blob/master/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L557

When we have to transmit the current ID downstream, you're passing the `Activity.Current.Id` from the currently running activity to become the new activity's parent ID. This creates a directed acyclic graph.

Now, for searching purposes, that's a bit different. The [`traceparent`](https://www.w3.org/TR/trace-context/#traceparent-header) value on the wire actually contains 4 parts:

- version
- trace-id
- parent-id
- trace-flags

The "full chain of custody" is the `trace-id` value, which if you notice above, does not change from span to span. The second value, `parent-id`, represents the ID of the parent, commonly known as the "span-id". Tracing systems let you search both of these values - the trace ID, and the span ID.

**Comment by buvinghausen** [comment]
Thanks for the clarification Jimmy.
